// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE1.Data;

#nullable disable

namespace SE1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SE1.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Location = "A4-502",
                            Name = "HP Color LaserJet Pro"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Location = "C6-102",
                            Name = "Brother MFC-J23188WC"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Location = "B1-212",
                            Name = "HP DeskJet 2440"
                        });
                });

            modelBuilder.Entity("SE1.Models.Printer2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Printer2s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = "active",
                            Location = "A4-502",
                            Name = "HP Color LaserJet Pro"
                        },
                        new
                        {
                            Id = 2,
                            Active = "active",
                            Location = "C6-102",
                            Name = "Brother MFC-J23188WC"
                        },
                        new
                        {
                            Id = 3,
                            Active = "active",
                            Location = "B1-212",
                            Name = "HP DeskJet 2440"
                        });
                });

            modelBuilder.Entity("SE1.Models.Request", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deliver_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Paper")
                        .HasColumnType("int");

                    b.HasKey("RId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            RId = 1,
                            Date = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deliver_date = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document_name = "Doc1",
                            Paper = 20
                        },
                        new
                        {
                            RId = 2,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deliver_date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document_name = "Doc2",
                            Paper = 18
                        },
                        new
                        {
                            RId = 3,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deliver_date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document_name = "Doc3",
                            Paper = 13
                        },
                        new
                        {
                            RId = 4,
                            Date = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deliver_date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document_name = "Doc4",
                            Paper = 25
                        });
                });

            modelBuilder.Entity("SE1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "dat.nguyentrinh1801@hcmut.edu.vn",
                            Name = "Dat Nguyen",
                            Password = "123456",
                            Phone = 347909369L
                        },
                        new
                        {
                            Id = 2,
                            Email = "khanh.phannguyen@hcmut.edu.vn",
                            Name = "Khanh Phan",
                            Password = "123456",
                            Phone = 965221701L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
